/*
 * File:           C:\Users\Jeroen\Jottacloud\DIY\Elektronica\ESPPreamp\Software\esppreamp\src\sigmastudio\export\ESPPreamp_IC_1_PARAM.h
 *
 * Created:        Saturday, October 4, 2025 5:57:10 PM
 * Description:    ESPPreamp:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2025 Analog Devices, Inc. All rights reserved.
 */
#ifndef __ESPPREAMP_IC_1_PARAM_H__
#define __ESPPREAMP_IC_1_PARAM_H__


/* Module ASYMMETRY - DC Input Entry*/
#define MOD_DSPDISTORTION_ASYMMETRY_COUNT              1
#define MOD_DSPDISTORTION_ASYMMETRY_DEVICE             "IC1"
#define MOD_DSPDISTORTION_ASYMMETRY_DCINPALG1_ADDR     0
#define MOD_DSPDISTORTION_ASYMMETRY_DCINPALG1_FIXPT    0x000CCCCC
#define MOD_DSPDISTORTION_ASYMMETRY_DCINPALG1_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.1)
#define MOD_DSPDISTORTION_ASYMMETRY_DCINPALG1_TYPE     SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1 - Gain*/
#define MOD_GAIN1_COUNT                                1
#define MOD_GAIN1_DEVICE                               "IC1"
#define MOD_GAIN1_GAIN1940ALGNS1_ADDR                  1
#define MOD_GAIN1_GAIN1940ALGNS1_FIXPT                 0x00800000
#define MOD_GAIN1_GAIN1940ALGNS1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_GAIN1_GAIN1940ALGNS1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module LOWCUT - General (1st order)*/
#define MOD_PREGAIN_LOWCUT_COUNT                       3
#define MOD_PREGAIN_LOWCUT_DEVICE                      "IC1"
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB00_ADDR          2
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB00_FIXPT         0x007F5677
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994826299150498)
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB00_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB10_ADDR          3
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB10_FIXPT         0xFF80A989
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB10_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.994826299150498)
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMB10_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMA00_ADDR          4
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMA00_FIXPT         0x007EACEF
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMA00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.989652598300996)
#define MOD_PREGAIN_LOWCUT_ALG0_PARAMA00_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module LOWCUT2 - General (1st order)*/
#define MOD_PREGAIN_LOWCUT2_COUNT                      3
#define MOD_PREGAIN_LOWCUT2_DEVICE                     "IC1"
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB00_ADDR         5
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB00_FIXPT        0x007F5677
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB00_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994826299150498)
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB00_TYPE         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB10_ADDR         6
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB10_FIXPT        0xFF80A989
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB10_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.994826299150498)
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMB10_TYPE         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMA00_ADDR         7
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMA00_FIXPT        0x007EACEF
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMA00_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.989652598300996)
#define MOD_PREGAIN_LOWCUT2_ALG0_PARAMA00_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module LOWCUT3 - General (1st order)*/
#define MOD_PREGAIN_LOWCUT3_COUNT                      3
#define MOD_PREGAIN_LOWCUT3_DEVICE                     "IC1"
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB00_ADDR         8
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB00_FIXPT        0x007F5677
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB00_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994826299150498)
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB00_TYPE         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB10_ADDR         9
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB10_FIXPT        0xFF80A989
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB10_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.994826299150498)
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMB10_TYPE         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMA00_ADDR         10
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMA00_FIXPT        0x007EACEF
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMA00_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.989652598300996)
#define MOD_PREGAIN_LOWCUT3_ALG0_PARAMA00_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module LOWCUT4 - General (1st order)*/
#define MOD_PREGAIN_LOWCUT4_COUNT                      3
#define MOD_PREGAIN_LOWCUT4_DEVICE                     "IC1"
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB00_ADDR         11
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB00_FIXPT        0x007F5677
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB00_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994826299150498)
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB00_TYPE         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB10_ADDR         12
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB10_FIXPT        0xFF80A989
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB10_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.994826299150498)
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMB10_TYPE         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMA00_ADDR         13
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMA00_FIXPT        0x007EACEF
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMA00_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.989652598300996)
#define MOD_PREGAIN_LOWCUT4_ALG0_PARAMA00_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module ORDER - Mono Switch Nx1*/
#define MOD_PREGAIN_ORDER_COUNT                        2
#define MOD_PREGAIN_ORDER_DEVICE                       "IC1"
#define MOD_PREGAIN_ORDER_ALG0_MONOSWSLEW_ADDR         14
#define MOD_PREGAIN_ORDER_ALG0_MONOSWSLEW_FIXPT        0x00000000
#define MOD_PREGAIN_ORDER_ALG0_MONOSWSLEW_VALUE        SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_PREGAIN_ORDER_ALG0_MONOSWSLEW_TYPE         SIGMASTUDIOTYPE_INTEGER
#define MOD_PRES_ORDER_ALG0_MONOSWSLEW_ADDR            58
#define MOD_PRES_ORDER_ALG0_MONOSWSLEW_FIXPT           0x00000000
#define MOD_PRES_ORDER_ALG0_MONOSWSLEW_VALUE           SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_PRES_ORDER_ALG0_MONOSWSLEW_TYPE            SIGMASTUDIOTYPE_INTEGER

/* Module BYPASS - Mono Switch Nx1*/
#define MOD_PREGAIN_BYPASS_COUNT                       3
#define MOD_PREGAIN_BYPASS_DEVICE                      "IC1"
#define MOD_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 15
#define MOD_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 16
#define MOD_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_BYPASS_ALG0_MONOSWSLEW_ADDR  28
#define MOD_DSPDISTORTION_BYPASS_ALG0_MONOSWSLEW_FIXPT 0x00000001
#define MOD_DSPDISTORTION_BYPASS_ALG0_MONOSWSLEW_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_DSPDISTORTION_BYPASS_ALG0_MONOSWSLEW_TYPE  SIGMASTUDIOTYPE_INTEGER

/* Module GAIN1 - Gain*/
#define MOD_DSPDISTORTION_GAIN1_COUNT                  1
#define MOD_DSPDISTORTION_GAIN1_DEVICE                 "IC1"
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_ADDR    17
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_FIXPT   0x0194C583
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.16227766016838)
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module GAIN2 - Gain*/
#define MOD_DSPDISTORTION_GAIN2_COUNT                  1
#define MOD_DSPDISTORTION_GAIN2_DEVICE                 "IC1"
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_ADDR    18
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_FIXPT   0x02818508
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(5.01187233627272)
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module GAIN3 - Gain*/
#define MOD_DSPDISTORTION_GAIN3_COUNT                  1
#define MOD_DSPDISTORTION_GAIN3_DEVICE                 "IC1"
#define MOD_DSPDISTORTION_GAIN3_GAIN1940ALGNS6_ADDR    19
#define MOD_DSPDISTORTION_GAIN3_GAIN1940ALGNS6_FIXPT   0x00800000
#define MOD_DSPDISTORTION_GAIN3_GAIN1940ALGNS6_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DSPDISTORTION_GAIN3_GAIN1940ALGNS6_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module NxM Mixer1 - NxM Mixer*/
#define MOD_DSPDISTORTION_NXMMIXER1_COUNT              2
#define MOD_DSPDISTORTION_NXMMIXER1_DEVICE             "IC1"
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10000_ADDR 20
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10000_FIXPT 0x00800000
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10000_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10000_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10001_ADDR 21
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10001_FIXPT 0x00800000
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10001_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DSPDISTORTION_NXMMIXER1_ALG0_NXNMIXER1940ALG10001_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module SoftClip1 - Standard Cubic*/
#define MOD_DSPDISTORTION_SOFTCLIP1_COUNT              4
#define MOD_DSPDISTORTION_SOFTCLIP1_DEVICE             "IC1"
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_ADDR 22
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_FIXPT 0x00800000
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_ADDR 23
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_FIXPT 0x00800000
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_ADDR 24
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_FIXPT 0x002AAAAA
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.333333333333333)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_ADDR 25
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_FIXPT 0x00555555
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.666666666666667)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB1 - DC Blocking*/
#define MOD_DSPDISTORTION_DCB1_COUNT                   1
#define MOD_DSPDISTORTION_DCB1_DEVICE                  "IC1"
#define MOD_DSPDISTORTION_DCB1_DCBLOCKALGDOUBLEPREC1POLE_ADDR 26
#define MOD_DSPDISTORTION_DCB1_DCBLOCKALGDOUBLEPREC1POLE_FIXPT 0x007FFCB9
#define MOD_DSPDISTORTION_DCB1_DCBLOCKALGDOUBLEPREC1POLE_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DSPDISTORTION_DCB1_DCBLOCKALGDOUBLEPREC1POLE_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module VOLUME - Single Volume*/
#define MOD_DSPDISTORTION_VOLUME_COUNT                 1
#define MOD_DSPDISTORTION_VOLUME_DEVICE                "IC1"
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_ADDR   27
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_FIXPT  0x00800000
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_TYPE   SIGMASTUDIOTYPE_FIXPOINT

/* Module SW vol 1 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL1_COUNT                               2
#define MOD_SWVOL1_DEVICE                              "IC1"
#define MOD_SWVOL1_ALG0_TARGET_ADDR                    29
#define MOD_SWVOL1_ALG0_TARGET_FIXPT                   0x00800000
#define MOD_SWVOL1_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SWVOL1_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL1_ALG0_STEP_ADDR                      30
#define MOD_SWVOL1_ALG0_STEP_FIXPT                     0x00000800
#define MOD_SWVOL1_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL1_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

/* Module MID1 - Medium Size Eq*/
#define MOD_POSTGAIN_MID1_COUNT                        5
#define MOD_POSTGAIN_MID1_DEVICE                       "IC1"
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B0_ADDR          31
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B0_FIXPT         0x007E3017
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B0_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.985842699730623)
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B0_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B1_ADDR          32
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B1_FIXPT         0xFF08E02C
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B1_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.93065884294655)
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B1_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B2_ADDR          33
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B2_FIXPT         0x0079468E
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B2_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.947465675152393)
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_B2_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A0_ADDR          34
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A0_FIXPT         0x00F71FD4
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A0_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.93065884294655)
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A0_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A1_ADDR          35
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A1_FIXPT         0xFF88895A
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A1_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.933308374883016)
#define MOD_POSTGAIN_MID1_ALG0_STAGE0_A1_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module MID2 - Medium Size Eq*/
#define MOD_POSTGAIN_MID2_COUNT                        5
#define MOD_POSTGAIN_MID2_DEVICE                       "IC1"
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B0_ADDR          36
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B0_FIXPT         0x007EF2AA
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B0_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.991780571848763)
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B0_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B1_ADDR          37
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B1_FIXPT         0xFF07F9EC
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B1_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.93768552201106)
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B1_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B2_ADDR          38
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B2_FIXPT         0x00796A8C
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B2_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.948564125133659)
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_B2_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A0_ADDR          39
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A0_FIXPT         0x00F80614
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A0_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.93768552201106)
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A0_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A1_ADDR          40
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A1_FIXPT         0xFF87A2C9
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A1_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.940344696982422)
#define MOD_POSTGAIN_MID2_ALG0_STAGE0_A1_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_TONECONTROL - General (2nd order)*/
#define MOD_POSTGAIN_PO_TONECONTROL_COUNT              5
#define MOD_POSTGAIN_PO_TONECONTROL_DEVICE             "IC1"
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_ADDR 41
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_FIXPT 0xFF55F870
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.32835584719983)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_ADDR 42
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_FIXPT 0x01564E55
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.67426555857715)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_ADDR 43
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_FIXPT 0xFF5425B2
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.34259972408618)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_ADDR 44
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_FIXPT 0x00F1FECC
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.89058836810461)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_ADDR 45
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_FIXPT 0xFF8DA089
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.893538397383039)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module PRESENCE - General (1st order)*/
#define MOD_PRES_PRESENCE_COUNT                        3
#define MOD_PRES_PRESENCE_DEVICE                       "IC1"
#define MOD_PRES_PRESENCE_ALG0_PARAMB00_ADDR           46
#define MOD_PRES_PRESENCE_ALG0_PARAMB00_FIXPT          0x003D2F00
#define MOD_PRES_PRESENCE_ALG0_PARAMB00_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.477996906703285)
#define MOD_PRES_PRESENCE_ALG0_PARAMB00_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE_ALG0_PARAMB10_ADDR           47
#define MOD_PRES_PRESENCE_ALG0_PARAMB10_FIXPT          0x00000000
#define MOD_PRES_PRESENCE_ALG0_PARAMB10_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PRES_PRESENCE_ALG0_PARAMB10_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE_ALG0_PARAMA00_ADDR           48
#define MOD_PRES_PRESENCE_ALG0_PARAMA00_FIXPT          0x0042D0FF
#define MOD_PRES_PRESENCE_ALG0_PARAMA00_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.522003093296715)
#define MOD_PRES_PRESENCE_ALG0_PARAMA00_TYPE           SIGMASTUDIOTYPE_FIXPOINT

/* Module PRESENCE2 - General (1st order)*/
#define MOD_PRES_PRESENCE2_COUNT                       3
#define MOD_PRES_PRESENCE2_DEVICE                      "IC1"
#define MOD_PRES_PRESENCE2_ALG0_PARAMB00_ADDR          49
#define MOD_PRES_PRESENCE2_ALG0_PARAMB00_FIXPT         0x003D2F00
#define MOD_PRES_PRESENCE2_ALG0_PARAMB00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.477996906703285)
#define MOD_PRES_PRESENCE2_ALG0_PARAMB00_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE2_ALG0_PARAMB10_ADDR          50
#define MOD_PRES_PRESENCE2_ALG0_PARAMB10_FIXPT         0x00000000
#define MOD_PRES_PRESENCE2_ALG0_PARAMB10_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PRES_PRESENCE2_ALG0_PARAMB10_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE2_ALG0_PARAMA00_ADDR          51
#define MOD_PRES_PRESENCE2_ALG0_PARAMA00_FIXPT         0x0042D0FF
#define MOD_PRES_PRESENCE2_ALG0_PARAMA00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.522003093296715)
#define MOD_PRES_PRESENCE2_ALG0_PARAMA00_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module PRESENCE3 - General (1st order)*/
#define MOD_PRES_PRESENCE3_COUNT                       3
#define MOD_PRES_PRESENCE3_DEVICE                      "IC1"
#define MOD_PRES_PRESENCE3_ALG0_PARAMB00_ADDR          52
#define MOD_PRES_PRESENCE3_ALG0_PARAMB00_FIXPT         0x003D2F00
#define MOD_PRES_PRESENCE3_ALG0_PARAMB00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.477996906703285)
#define MOD_PRES_PRESENCE3_ALG0_PARAMB00_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE3_ALG0_PARAMB10_ADDR          53
#define MOD_PRES_PRESENCE3_ALG0_PARAMB10_FIXPT         0x00000000
#define MOD_PRES_PRESENCE3_ALG0_PARAMB10_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PRES_PRESENCE3_ALG0_PARAMB10_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE3_ALG0_PARAMA00_ADDR          54
#define MOD_PRES_PRESENCE3_ALG0_PARAMA00_FIXPT         0x0042D0FF
#define MOD_PRES_PRESENCE3_ALG0_PARAMA00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.522003093296715)
#define MOD_PRES_PRESENCE3_ALG0_PARAMA00_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module PRESENCE4 - General (1st order)*/
#define MOD_PRES_PRESENCE4_COUNT                       3
#define MOD_PRES_PRESENCE4_DEVICE                      "IC1"
#define MOD_PRES_PRESENCE4_ALG0_PARAMB00_ADDR          55
#define MOD_PRES_PRESENCE4_ALG0_PARAMB00_FIXPT         0x003D2F00
#define MOD_PRES_PRESENCE4_ALG0_PARAMB00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.477996906703285)
#define MOD_PRES_PRESENCE4_ALG0_PARAMB00_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE4_ALG0_PARAMB10_ADDR          56
#define MOD_PRES_PRESENCE4_ALG0_PARAMB10_FIXPT         0x00000000
#define MOD_PRES_PRESENCE4_ALG0_PARAMB10_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PRES_PRESENCE4_ALG0_PARAMB10_TYPE          SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PRES_PRESENCE4_ALG0_PARAMA00_ADDR          57
#define MOD_PRES_PRESENCE4_ALG0_PARAMA00_FIXPT         0x0042D0FF
#define MOD_PRES_PRESENCE4_ALG0_PARAMA00_VALUE         SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.522003093296715)
#define MOD_PRES_PRESENCE4_ALG0_PARAMA00_TYPE          SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_BYPASS - Mono Switch Nx1*/
#define MOD_POSTGAIN_PO_BYPASS_COUNT                   2
#define MOD_POSTGAIN_PO_BYPASS_DEVICE                  "IC1"
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 59
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 60
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_VOLUME - Single SW slew vol (adjustable)*/
#define MOD_PO_VOLUME_COUNT                            2
#define MOD_PO_VOLUME_DEVICE                           "IC1"
#define MOD_PO_VOLUME_ALG0_TARGET_ADDR                 61
#define MOD_PO_VOLUME_ALG0_TARGET_FIXPT                0x003D43C0
#define MOD_PO_VOLUME_ALG0_TARGET_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.478630092322639)
#define MOD_PO_VOLUME_ALG0_TARGET_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PO_VOLUME_ALG0_STEP_ADDR                   62
#define MOD_PO_VOLUME_ALG0_STEP_FIXPT                  0x00000800
#define MOD_PO_VOLUME_ALG0_STEP_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_PO_VOLUME_ALG0_STEP_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1_2 - Gain*/
#define MOD_GAIN1_2_COUNT                              1
#define MOD_GAIN1_2_DEVICE                             "IC1"
#define MOD_GAIN1_2_GAIN1940ALGNS7_ADDR                63
#define MOD_GAIN1_2_GAIN1940ALGNS7_FIXPT               0x00FF64C1
#define MOD_GAIN1_2_GAIN1940ALGNS7_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99526231496888)
#define MOD_GAIN1_2_GAIN1940ALGNS7_TYPE                SIGMASTUDIOTYPE_FIXPOINT

#endif
